@extends('layouts.app')
<!--Applied Visual Design Page -->
@section('content')
      <h2>{{$title}}</h2>
      <p>Visual Design in web development is a broad topic. It combines typography, color theory, graphics, animation, and page layout to help deliver a site's message. The definition of good design is a well-discussed subject, with many books on the theme.</p>
      <p>At a basic level, most web content provides a user with information. The visual design of the page can influence its presentation and a user's experience. In web development, HTML gives structure and semantics to a page's content, and CSS controls the layout and appearance of it.</p>
      <p>This section covers some of the basic tools developers use to create their own visual designs.</p>
      <h4>Upcoming Lessons</h4>
      <ul class="list-group">
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-visual-balance-using-the-text-align-property/" target="_blank">Create Visual Balance Using the text-align Property</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-width-of-an-element-using-the-width-property/" target="_blank">Adjust the Width of an Element Using the width Property</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-height-of-an-element-using-the-height-property/" target="_blank">Adjust the Height of an Element Using the height Property</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-strong-tag-to-make-text-bold/" target="_blank">Use the strong Tag to Make Text Bold</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-u-tag-to-underline-text/" target="_blank">Use the u Tag to Underline Text</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-em-tag-to-italicize-text/" target="_blank">Use the em Tag to Italicize Text</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-s-tag-to-strikethrough-text/" target="_blank">Use the s Tag to Strikethrough Text</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element/" target="_blank">Create a Horizontal Line Using the hr Element</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-background-color-property-of-text/" target="_blank">Adjust the background-color Property of Text</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-size-of-a-header-versus-a-paragraph-tag/" target="_blank">Adjust the Size of a Header Versus a Paragraph Tag</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/add-a-box-shadow-to-a-card-like-element/" target="_blank">Add a box-shadow to a Card-like Element</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element/" target="_blank">Decrease the Opacity of an Element</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-text-transform-property-to-make-text-uppercase/" target="_blank">Use the text-transform Property to Make Text Uppercase</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements/" target="_blank">Set the font-size for Multiple Heading Elements</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/set-the-font-weight-for-multiple-heading-elements/" target="_blank">Set the font-weight for Multiple Heading Elements</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/set-the-font-size-of-paragraph-text/" target="_blank">Set the font-size of Paragraph Text</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/set-the-line-height-of-paragraphs/" target="_blank">Set the line-height of Paragraphs</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-hover-state-of-an-anchor-tag/" target="_blank">Adjust the Hover State of an Anchor Tag</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/change-an-elements-relative-position/" target="_blank">Change an Element's Relative Position</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/move-a-relatively-positioned-element-with-css-offsets/" target="_blank">Move a Relatively Positioned Element with CSS Offsets</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/lock-an-element-to-its-parent-with-absolute-positioning/" target="_blank">Lock an Element to its Parent with Absolute Positioning</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/lock-an-element-to-the-browser-window-with-fixed-positioning/" target="_blank">Lock an Element to the Browser Window with Fixed Positioning</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/push-elements-left-or-right-with-the-float-property/" target="_blank">Push Elements Left or Right with the float Property</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/change-the-position-of-overlapping-elements-with-the-z-index-property/" target="_blank">Change the Position of Overlapping Elements with the z-index Property</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/center-an-element-horizontally-using-the-margin-property/" target="_blank">Center an Element Horizontally Using the margin Property</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/learn-about-complementary-colors/" target="_blank">Learn about Complementary Colors</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/learn-about-tertiary-colors/" target="_blank">Learn about Tertiary Colors</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-color-of-various-elements-to-complementary-colors/" target="_blank">Adjust the Color of Various Elements to Complementary Colors</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-hue-of-a-color/" target="_blank">Adjust the Hue of a Color</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color/" target="_blank">Adjust the Tone of a Color</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-gradual-css-linear-gradient/" target="_blank">Create a Gradual CSS Linear Gradient</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-a-css-linear-gradient-to-create-a-striped-element/" target="_blank">Use a CSS Linear Gradient to Create a Striped Element</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image/" target="_blank">Create Texture by Adding a Subtle Pattern as a Background Image</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-css-transform-scale-property-to-change-the-size-of-an-element/" target="_blank">Use the CSS Transform scale Property to Change the Size of an Element</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-css-transform-scale-property-to-scale-an-element-on-hover/" target="_blank">Use the CSS Transform scale Property to Scale an Element on Hover</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-css-transform-property-skewx-to-skew-an-element-along-the-x-axis/" target="_blank">Use the CSS Transform Property skewX to Skew an Element Along the X-Axis</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-css-transform-property-skewy-to-skew-an-element-along-the-y-axis/" target="_blank">Use the CSS Transform Property skewY to Skew an Element Along the Y-Axis</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-graphic-using-css/" target="_blank">Create a Graphic Using CSS</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-more-complex-shape-using-css-and-html/" target="_blank">Create a More Complex Shape Using CSS and HTML</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/learn-how-the-css-keyframes-and-animation-properties-work/" target="_blank">Learn How the CSS @keyframes and animation Properties Work</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-css-animation-to-change-the-hover-state-of-a-button/" target="_blank">Use CSS Animation to Change the Hover State of a Button</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/modify-fill-mode-of-an-animation/" target="_blank">Modify Fill Mode of an Animation</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-movement-using-css-animation/" target="_blank">Create Movement Using CSS Animation</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-visual-direction-by-fading-an-element-from-left-to-right/" target="_blank">Create Visual Direction by Fading an Element from Left to Right</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/animate-elements-continually-using-an-infinite-animation-count/" target="_blank">Animate Elements Continually Using an Infinite Animation Count</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/make-a-css-heartbeat-using-an-infinite-animation-count/" target="_blank">Make a CSS Heartbeat using an Infinite Animation Count</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/animate-elements-at-variable-rates/" target="_blank">Animate Elements at Variable Rates</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/animate-multiple-elements-at-variable-rates/" target="_blank">Animate Multiple Elements at Variable Rates</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/change-animation-timing-with-keywords/" target="_blank">Change Animation Timing with Keywords</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/learn-how-bezier-curves-work/" target="_blank">Learn How Bezier Curves Work</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-a-bezier-curve-to-move-a-graphic/" target="_blank">Use a Bezier Curve to Move a Graphic</a></li>
        <li class="list-group-item"><a href="https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/make-motion-more-natural-using-a-bezier-curve/" target="_blank">Make Motion More Natural Using a Bezier Curve</a></li>
      </ul>  
@endsection      